import type { BoardFaqItem } from '@/components/custom-ui/board-faq';

export const TEMPLATE_PAGE_PATH = '/handball-statistik-excel-vorlage';

/**
 * The template file itself. Generated by
 * `scripts/generate-handball-statistik-vorlage.py` – regenerate it there rather
 * than editing the binary, so the formulas stay reproducible.
 */
export const TEMPLATE_FILE = {
  path: '/downloads/handball-statistik-vorlage.xlsx',
  name: 'handball-statistik-vorlage.xlsx',
  /** Capacities of the shipped file – keep in sync with the generator script. */
  actionRows: 400,
  games: 30,
  squadSlots: 20,
  sheets: ['Kader', 'Spielprotokoll', 'Auswertung', 'Saison'],
} as const;

export interface MetricGroup {
  sheet: string;
  description: string;
  metrics: string[];
}

/** What the four sheets track – each entry exists in the shipped file. */
export const TEMPLATE_METRICS: MetricGroup[] = [
  {
    sheet: 'Kader',
    description:
      'Deine Mannschaft mit Rückennummer, Name, Position und Jahrgang. Die Nummer ist der Schlüssel: Alle anderen Blätter ziehen sich den Namen automatisch daraus.',
    metrics: ['Rückennummer', 'Name', 'Position (Auswahlliste)', 'Jahrgang', 'Notiz'],
  },
  {
    sheet: 'Spielprotokoll',
    description:
      'Eine Zeile pro Aktion – so, wie es am Spielfeldrand tatsächlich passiert. Aktion und Wurfzone wählst du aus einer Liste, den Namen musst du nie tippen.',
    metrics: [
      'Tor und Fehlwurf',
      'Siebenmeter (Tor / Fehlwurf)',
      'Parade und Gegentor',
      'Assist',
      'Technischer Fehler',
      '2 Minuten, Gelb, Rot',
      'Wurfzone: Außen, Kreis, Rückraum, Durchbruch, Tempogegenstoß, Siebenmeter',
    ],
  },
  {
    sheet: 'Auswertung',
    description:
      'Ein Spiel, alle Spieler, fertig gerechnet. Du trägst oben die Spielbezeichnung ein – der Rest steht da.',
    metrics: [
      'Würfe und Tore pro Spieler',
      'Wurfquote in Prozent',
      'Siebenmeter-Quote',
      'Assists, technische Fehler, Zeitstrafen',
      '± (Tore inkl. 7 m minus Fehlwürfe minus technische Fehler)',
      'Paraden, Gegentore und Paradenquote des Torwarts',
      'Mannschaftszeile mit allen Summen und Quoten',
    ],
  },
  {
    sheet: 'Saison',
    description:
      'Die Spieleliste der Saison und darunter die rollierenden Werte jedes Spielers über alle erfassten Partien.',
    metrics: [
      'Eigene Tore und Gegentore pro Spiel',
      'Anzahl Spiele pro Spieler',
      'Würfe, Tore und Wurfquote über die Saison',
      'Siebenmeter-Bilanz',
      'Technische Fehler und Zeitstrafen',
      'Paradenquote über die Saison',
    ],
  },
];

export interface HowToStep {
  name: string;
  text: string;
}

/** Mirrors the visible steps AND the HowTo JSON-LD – keep both in sync. */
export const TEMPLATE_HOW_TO: HowToStep[] = [
  {
    name: 'Kader einmal eintragen',
    text: 'Trag im Blatt „Kader“ Rückennummer, Name und Position deiner Spieler ein. Das machst du einmal pro Saison. Die vier grau hinterlegten Beispielzeilen überschreibst du einfach.',
  },
  {
    name: 'Spiel benennen',
    text: 'Gib dem Spiel im Blatt „Saison“ eine kurze Bezeichnung, zum Beispiel Sp1, dazu Datum und Gegner. Genau diese Bezeichnung nutzt du gleich im Protokoll.',
  },
  {
    name: 'Jede Aktion als Zeile erfassen',
    text: 'Im Blatt „Spielprotokoll“ trägst du pro Aktion eine Zeile ein: Spiel, Minute, Rückennummer, Aktion und Wurfzone. Der Name erscheint automatisch. Aktion und Zone wählst du aus der Liste – ein Klick statt tippen.',
  },
  {
    name: 'Halbzeit nutzen',
    text: 'Sieh in der Pause kurz ins Blatt „Auswertung“. Wurfquoten und Paradenquote stehen dort fertig – das reicht für eine Ansage, die auf Zahlen statt auf Gefühl beruht.',
  },
  {
    name: 'Nach dem Spiel auswerten',
    text: 'Trag oben in der Auswertung die Spielbezeichnung ein und drucke das Blatt aus oder teile es. Das Saisonblatt aktualisiert sich mit jedem erfassten Spiel von selbst.',
  },
];

export interface ExcelLimit {
  title: string;
  text: string;
}

/** The honest limits of a spreadsheet – no strawman, these are the real ones. */
export const EXCEL_LIMITS: ExcelLimit[] = [
  {
    title: 'Auf der Bank tippst du nicht in Zellen',
    text: 'Am Tablet triffst du im Stehen keine Zelle, während der Gegner kontert. In der Praxis führt das dazu, dass du mitschreibst, was du noch im Kopf hast – und das ist nach einer Viertelstunde nicht mehr viel.',
  },
  {
    title: 'Abtippen kostet dich den Sonntag',
    text: 'Wer den Zettel abends überträgt, macht die Arbeit zweimal. Und jede Übertragung erzeugt Fehler: Ein Fehlwurf, der beim Abtippen untergeht, hebt die Wurfquote und du steuerst dein Training nach einer Zahl, die es nie gab.',
  },
  {
    title: 'Kein Wurfbild',
    text: 'Eine Tabelle sagt dir, dass 40 Prozent der Rückraumwürfe drin waren. Sie sagt dir nicht, dass alle Fehlwürfe aus derselben Ecke kamen. Wo geworfen wurde, sieht man nur auf einem Feld – nicht in einer Zelle.',
  },
  {
    title: 'Kein Verlauf pro Spieler',
    text: 'Das Saisonblatt summiert, aber es zeigt keine Kurve. Ob eine Rückraumspielerin über sechs Spiele besser wird oder nur ein gutes Spiel hatte, liest du aus Summen nicht heraus.',
  },
  {
    title: 'Am dritten Spieltag öffnet sie keiner mehr',
    text: 'Das ist das eigentliche Problem. Die Datei liegt auf einem Laptop, den Co-Trainer nicht hat, in einer Version, die niemand kennt. Nach dem dritten Spieltag ist sie ein Archiv, kein Werkzeug.',
  },
];

export const TEMPLATE_FAQS: BoardFaqItem[] = [
  {
    question: 'Ist die Excel-Vorlage wirklich kostenlos?',
    answer:
      'Ja. Der Download startet sofort, ohne Anmeldung, ohne E-Mail-Adresse und ohne Newsletter. Du kannst die Datei behalten, anpassen und im Verein weitergeben.',
  },
  {
    question: 'Mit welchen Programmen kann ich die Vorlage öffnen?',
    answer:
      'Mit Microsoft Excel, LibreOffice Calc und Google Tabellen. Die Formeln sind bewusst schlicht gehalten (COUNTIFS, INDEX/MATCH, SUMPRODUCT), damit sie überall rechnen. In Apple Numbers funktionieren die Berechnungen ebenfalls, einzelne Auswahllisten können beim Import verloren gehen.',
  },
  {
    question: 'Welche Kennzahlen rechnet die Vorlage automatisch aus?',
    answer:
      'Würfe, Tore und Wurfquote pro Spieler, die Siebenmeter-Quote, Assists, technische Fehler und Zeitstrafen, ein ± je Spieler sowie Paraden, Gegentore und Paradenquote des Torwarts. Dazu Mannschaftssummen pro Spiel und rollierende Saisonwerte.',
  },
  {
    question: 'Was zählt als Wurf?',
    answer:
      'Jeder Torabschluss: Tor, gehaltener Ball, Pfosten und klarer Fehlwurf. Ein technischer Fehler ohne Abschluss ist kein Wurf und fließt nicht in die Wurfquote ein. Siebenmeter führt die Vorlage getrennt, weil sie die Feldquote sonst verzerren.',
  },
  {
    question: 'Reicht die Vorlage für eine ganze Saison?',
    answer:
      'Sie ist auf 400 erfasste Aktionen, 30 Spiele und 20 Kaderplätze ausgelegt. Für eine Jugend- oder Amateursaison reicht das in der Regel; wer mehr braucht, zieht die Formeln einfach weiter nach unten.',
  },
  {
    question: 'Muss ich den Newsletter abonnieren, um die Datei zu bekommen?',
    answer:
      'Nein. Der Download ist von allem anderen unabhängig. Der Newsletter ist ein freiwilliges Angebot daneben – das Häkchen ist nicht vorausgewählt, und ohne Häkchen bekommst du die Vorlage genauso.',
  },
];
