import type { BoardFaqItem } from '@/components/custom-ui/board-faq';
import { DE_MESSAGES } from '@/lib/messages';

export const TEMPLATE_PAGE_PATH = '/handball-statistik-excel-vorlage';

/**
 * The template file itself. Generated by
 * `scripts/generate-handball-statistik-vorlage.py` – regenerate it there rather
 * than editing the binary, so the formulas stay reproducible.
 *
 * The sheet names stay German in every language, because they are the tab
 * labels of the shipped file: a Polish reader told the analysis lives in
 * "Analiza" would look for a tab that is not there. The bundles name each sheet
 * with its German label and a translation in brackets.
 */
export const TEMPLATE_FILE = {
  path: '/downloads/handball-statistik-vorlage.xlsx',
  name: 'handball-statistik-vorlage.xlsx',
  /** Capacities of the shipped file – keep in sync with the generator script. */
  actionRows: 400,
  games: 30,
  squadSlots: 20,
  sheets: ['Kader', 'Spielprotokoll', 'Auswertung', 'Saison'],
} as const;

export interface MetricGroup {
  sheet: string;
  description: string;
  metrics: string[];
}

export interface HowToStep {
  name: string;
  text: string;
}

export interface ExcelLimit {
  title: string;
  text: string;
}

/**
 * The five filling steps in German, for the route's `HowTo` node — word for
 * word what the visible band shows a German reader.
 */
export const TEMPLATE_HOW_TO: HowToStep[] = DE_MESSAGES.templatePage.howTo.steps;

/** The visible FAQ in German, for the route's `FAQPage` node. */
export const TEMPLATE_FAQS: BoardFaqItem[] = DE_MESSAGES.templatePage.faq.items;
